config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
  end
  root to: "sessions#new"
  resources :tasks
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/label.rb
class Label < ApplicationRecord
  has_many :labellings, dependent: :destroy
  has_many :tasks, through: :labellings
end

app/models/labelling.rb
class Labelling < ApplicationRecord
  belongs_to :task, optional: true
  belongs_to :label, optional: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user, optional: true
  has_many :labellings, dependent: :destroy
  has_many :labels, through: :labellings

  enum status: { wait: 0, running: 1, completed: 2 }
  enum priority: { low: 0, middle: 1, high: 2 }

  scope :search_title, -> (title) {
    next if title.blank?
    where("title LIKE ?", "%#{title}%")}
  scope :search_status, -> (status) {
    next if status.blank?
    where(status: "#{status}")}
  scope :search_label, -> (label) {
    next if label.blank?
    joins(:labellings).where("labellings.label_id": label)}

  # scope :search_title_status, -> (title, status) { where("title LIKE ?", "%#{title}%").where(status: "#{status}")}

  validates :title, presence: true, length: { maximum: 50 }
  validates :explanation, presence: true, length: { maximum: 200 }
  validates :deadline, presence: true
  paginates_per 10
end

app/models/user.rb
class User < ApplicationRecord
  before_destroy :cant_be_absent_admin_destroy

  before_update :cant_be_absent_admin_update

  validates :name, presence: true, length: { maximum: 20 }
  validates :email, presence: true, length: { maximum: 40 }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }, uniqueness: true
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  has_many :tasks, dependent: :destroy

  private

  # destroyを止めようとするのはadminがtrueの状態
  def cant_be_absent_admin_destroy
    throw(:abort) if User.where(admin: 'true').count <= 1 && admin?
  end

  # updateを止めようとするのはadminがfalseの状態
  def cant_be_absent_admin_update
    throw(:abort) if User.where(admin: 'true').count == 1 && !admin?
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  skip_before_action :must_login
  before_action :if_not_admin

  def index
    @users = User.page(params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to admin_users_path, notice: "ユーザー<#{@user.name}>を登録しました"
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to admin_user_path(@user), notice: "更新しました"
    elsif User.where(admin: 'true').count == 0
      flash.now[:alert] = "管理者不在にはできません"
      render :edit
    else
      render :edit
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    if  @user.destroy
      redirect_to admin_users_path, notice: "ユーザー<#{@user.name}>を削除しました"
    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
  end

  def if_not_admin
    rescue403 unless current_user.admin?
    # raise Forbidden unless current_user.admin?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :must_login

  # Forbiddenというエラーを実装する
  # class Forbidden < ActionController::ActionControllerError
  # end
  #
  # # Forbiddenが発生したらresucue403メソッド
  # rescue_from Forbidden, with: :rescue403

  private

    # エラー発生時はapp/errors/forbbiden.html.erb を表示し、HTTPステータス403を返す
    def rescue403
      # @exception = e
      render template: 'errors/forbidden.html'
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :must_login, only: [:new, :create]
  # before_action :must_login, except: [:new, :create, :destroy]

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :get_id_task, only: [:show, :edit, :update, :destroy]


  def index
    if params[:task]
      @tasks = current_user.tasks
                            .search_title(params.dig(:task, :title))
                            .search_status(params.dig(:task, :status))
                            .search_label(params.dig(:task, :label_id))
                            .group(:id)
                            .page(params[:page])

    elsif params[:sort_by_deadline]
      @tasks = current_user.tasks.page(params[:page]).order(deadline: :desc)

    elsif params[:sort_by_priority]
      @tasks = current_user.tasks.page(params[:page]).order(priority: :desc)

    else
      @tasks = current_user.tasks.page(params[:page]).order(created_at: :desc)
    end
      # if params[:task]
      #   binding.pry
      #   if params[:task][:title] && params[:task][:status]
      #     binding.pry
      #     @tasks = current_user.tasks.search_title_status(params[:task][:title].params[:task][:status])
      #   elsif params[:task][:title].present?
      #     binding.pry
      #     @tasks = current_user.tasks.search_title(params[:task][:title])
      #   elsif params[:task][:status].present?
      #     binding.pry
      #     @tasks = current_user.tasks.search_status(params[:task][:status])
      #   elsif params[:task][:label_id].present?
      #     binding.pry
      #     labelling = Labelling.where(label_id: params[:label_id])
      #     @tasks = current_user.tasks.where(id: labelling.pluck(:task_id))
      #   end
        # @tasks = Task.where("title LIKE ?", "%#{ params[:task][:title] }%").where(status: "#{ params[:task][:status] }")
      # end
  end

  def new
    @task = Task.new
  end

  def create
    @task = current_user.tasks.build(task_params)
    if @task.save
      redirect_to task_path(@task), notice: "タスクを登録しました"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @task.update(task_params)
      redirect_to tasks_path, notice: "タスクを編集しました"
    else
      render :edit
    end
  end

  def show
  end

  def destroy
    @task.destroy
    redirect_to tasks_path, notice:  "タスクを削除しました"
  end

  private

  def task_params
    params.require(:task).permit(:title, :explanation, :deadline, :status, :search, :priority, :user_id, label_ids: [])
  end

  def get_id_task
    @task = current_user.tasks.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
skip_before_action :must_login, only: [:new, :create]

  def new
    if logged_in?
      redirect_to tasks_path
    else
      @user = User.new
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user.id), notice: "ユーザー'#{@user.name}'を登録しました"
    else
      render :new
    end
  end

  def show
    if current_user == User.find(params[:id])
      @user = User.find(params[:id])
    else
      redirect_to tasks_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end

  def must_login
    if current_user == nil
      redirect_to root_path
    end
  end
end

app/views/admin/users/edit.html.erb
<div class="flash_message">
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
  <% end %>
</div>

<h3><%= t('activerecord.models.user')+t('view.edit') %></h3>


<%= form_with(model: [:admin, @user], locale: true) do |f| %>

  <div class="">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="">
  <%= f.label :email %>
  <%= f.text_field :email %>
  </div>

  <div class="">
  <%= f.label :password %>
  <%= f.text_field :password %>
  </div>

  <div class="">
  <%= f.label :admin %>
  <%= f.check_box :admin %>
  管理者権限
  </div>

  <div class="">
  <%= f.label :password_confirmation %>
  <%= f.text_field :password_confirmation %>
  </div>

  <div class="">
  <%= f.submit t('view.update'), id:"update", class:'update' %>
  </div>

<% end %>

<p class="to_other_page">
  <%= link_to t('view.admin'), admin_users_path %></p>

app/views/admin/users/index.html.erb
<h3>ユーザー一覧</h3>

<div class="user_index">
  <table class="table_container">
    <tr>
      <th class="table_header"><%= t('view.name') %></th>
      <th class="table_header"><%= t('view.title_count') %></th>
      <th class="table_header"><%= t('view.email') %></th>
      <th class="table_header"><%= t('view.admin') %></th>
      <th class="table_header"><%= t('view.created_at') %></th>
      <th class="table_header"><%= t('view.updated_at') %></th>
      <th class="option_order"><%= t('view.edit') %></th>
      <th class="option_order"><%= t('view.destroy') %></th>
    </tr>

  <% @users.each do |user| %>

    <tr>
      <td id="user_title" class="user_data"><%= link_to user.name, admin_user_path(user.id) %></td>
      <td id="user_title" class="user_data"><%= link_to user.tasks.count, admin_user_path(user.id) %></td>
      <td id="user_email" class="user_data"><%= user.email %></td>
      <td class="user_data"><%= user.admin? ? '◯' : '-' %></td>
      <td class="user_data"><%= user.created_at %></td>
      <td class="user_data"><%= user.updated_at %></td>
      <td class="option_order"><%= link_to t('view.edit'), edit_admin_user_path(user.id) %></td>
      <td class="option_order">
        <%= link_to t('view.destroy'), [:admin, user], method: :delete, data: { confirm: t('view.destroy_confirm')} %></td>
    </tr>

  <% end %>
  </table>

  <%= paginate @users %>

  <p class="to_other_page"><%= link_to t('activerecord.models.user')+t('view.create'), new_admin_user_path %></p>
  <p class="to_other_page"><%= link_to t('view.index'), tasks_path %></p>


</div>

app/views/admin/users/new.html.erb
<h3><%= t('activerecord.models.user')+t('view.create') %></h3>

<%= form_with(model: [:admin, @user], locale: true) do |f| %>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <% @user.errors.full_messages.each do |msg| %>
      <p><%= msg %></p>
    <% end %>
  </div>
<% end %>

  <div class="">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="">
  <%= f.label :email %>
  <%= f.text_field :email %>
  </div>

  <div class="">
    <%= f.label :admin %>
    <%= f.check_box :admin %>
    管理者権限
  </div>

  <div class="">
  <%= f.label :password %>
  <%= f.text_field :password %>
  </div>

  <div class="">
  <%= f.label :password_confirmation %>
  <%= f.text_field :password_confirmation %>
  </div>

  <div class="">
  <%= f.submit t('view.create my account'), id:"create" %>
  <%#= f.button :button, type: :submit %>
  </div>

<% end %>

<p class="to_other_page">
  <%= link_to t('view.admin'), admin_users_path %></p>

app/views/admin/users/show.html.erb
<div class="flash_message">
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
  <% end %>
</div>

<h3><%= t('activerecord.models.user')+t('view.show') %></h3>

<div class="">
  <span><%= t('view.name') %></span>: <span class="user_data"><%= @user.name %></span>
</div>

<div class="">
  <span><%= t('view.email') %></span>: <span id="user_email" class="user_data"><%= @user.email %></span>
</div>

<p class="to_other_page">
  <%= link_to t('view.admin'), admin_users_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tasksapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width">
  </head>

  <body>

    <header class="header_container">
      <h2 id="header_title">TASKSapp</h2>
    </header>

    <main class="main_container">

      <div class="flash_message">
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: "#{key}") %>
        <% end %>
      </div>

      <div class="login_confirm">
        <% if logged_in? %>
          <%= link_to t('view.profile'), user_path(current_user.id) %>
          <%= link_to t('view.logout'), session_path(current_user.id), method: :delete %>
          <% if current_user.admin? %>
          <p class="to_other_page">
            <%= link_to t('view.admin'), admin_users_path %></p>
          <% end %>
        <% else %>
          <%= link_to t('view.signup'), new_user_path %>
        <% end %>
      </div>

    <%= yield %>
    </main>

  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: @task, local: true ) do |f| %>

  <% if @task.errors.any? %>
    <div id="error_explanation">
      <% @task.errors.full_messages.each do |msg| %>
        <p><%= msg %></p>
      <% end %>
    </div>
  <% end %>

  <div class="task_fill">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div class="task_fill">
    <%= f.label :explanation %><br>
    <%= f.text_area :explanation %>
  </div>

  <div class="task_fill">
    <%= f.label :deadline %><br>
    <%= f.text_field :deadline %>
  </div>

  <div class="task_fill">
    <%= f.label :status %><br>
    <%= f.select :status, Task.statuses.map { |k,v| [t("enums.task.status.#{k}"), k] }  %>
  </div>

  <div class="task_fill">
    <%= f.label :priority %><br>
    <%= f.select :priority, Task.priorities.map { |k,v| [t("enums.task.priority.#{k}"), k] }  %>
  </div>

  <div class="">
    <%= f.label :label %><br>
    <% Label.all.each do |l| %>
      <%= f.check_box :label_ids, { multiple: true, checked: l[:checked], disabled: l[:disabled], include_hidden: false }, l[:id] %><%= l.name %>
    <% end %>
  </div>

    <div class="button"><%= f.submit %></div>
<% end %>

app/views/tasks/edit.html.erb
<h3><%= t('view.edit') %></h3>

<%= render "form" %>

<p class="to_other_page"><%= link_to t('view.show'), task_path(@task) %></p>
<p class="to_other_page"><%= link_to t('view.index'), tasks_path %></p>

app/views/tasks/index.html.erb
<h3><%= link_to t('view.index'), tasks_path %></h3>

  <p><%= notice %></p>

  <div class="sort_by">
    <p class="to_other_page"><%= link_to t('view.sort_by_deadline'), tasks_path(sort_by_deadline: "true") %>
    </p>

    <p class="to_other_page"><%= link_to t('view.sort_by_priority'), tasks_path(sort_by_priority: "true") %>
    </p>
  </div>

  <div class="search_area">
    <%= form_with(model: Task.new, method: :get, url: tasks_path, local: true) do |f|%>
    <div class="search_item">
      <%= f.label t('view.title_search') %>
      <%= f.text_field :title %>
    </div>
    <div class="search_item">
      <%= f.label t('view.status_search') %>
      <%= f.select :status, Task.statuses.map { |k,v| [t("enums.task.status.#{k}"), k] }, include_blank: true %>
    </div>
    <div class="search_item">
      <% unless Label.all.blank? %>
        <%= f.label t('view.label_search') %>
        <%# model(=Label)を扱うセレクトボックス %>
        <%# <%= f.select(:label_id) do %>
          <%# <% Label.pluck(:name, :id).each do |l, k| %>
            <%# <%= content_tag(:option, l, value: k) %>
          <%# <% end %>
        <%# <% end %> 
        <%= f.select :label_id, Label.pluck(:name, :id).each { |l, k| content_tag(:option, l, value: k)}, {include_blank: true} %>
      <% end %>
    </div>
    <%# 情報の絞り込み %>
    <%= f.hidden_field :search, value: 'true' %>
    <div class="search_item">
      <%= f.submit t('helpers.submit.search'), name: nil %>
    </div>
    <% end %>
  </div>

  <div class="task_index">
    <table class="table_container">
      <tr>
        <th class="table_header"><%= t('view.title') %></th>
        <th class="table_header"><%= t('view.explanation') %></th>
        <th class="table_header"><%= t('view.deadline') %></th>
        <th class="table_header"><%= t('view.status') %></th>
        <th class="table_header"><%= t('view.priority') %></th>
        <th class="table_header"><%= t('view.label') %></th>
        <th class="option_order"><%= t('view.show') %></th>
        <th class="option_order"><%= t('view.edit') %></th>
        <th class="option_order"><%= t('view.destroy') %></th>
      </tr>

    <% @tasks.each do |task| %>

      <tr>
        <td id="task_title" class="task_data"><%= task.title %></td>
        <td class="task_data"><%= task.explanation %></td>
        <td class="task_data"><%= task.deadline %></td>
        <td class="task_data"><%= t("enums.task.status.#{task.status}") %></td>
        <td class="task_data"><%= t("enums.task.priority.#{task.priority}") %></td>
        <td class="task_data">
          <% task.labels.each do |label| %>
          <%= label.name %>
          <% end %>
        </td>
        <td class="option_order"><%= link_to t('view.show'), task_path(task.id) %></td>
        <td class="option_order"><%= link_to t('view.edit'), edit_task_path(task.id) %></td>
        <td class="option_order">
          <%= link_to t('view.destroy'), task_path(task.id), method: :delete, data: { confirm: t('view.destroy_confirm')} %></td>
      </tr>

    <% end %>
    </table>

    <%= paginate @tasks %>

    <p class="to_other_page"><%= link_to t('activerecord.models.task')+t('view.create'), new_task_path %></p>

  </div>

app/views/tasks/new.html.erb
<h3><%= t('view.create') %></h3>

<%= render "form" %>

<p class="to_other_page"><%= link_to t('view.index'), tasks_path %></p>

app/views/tasks/show.html.erb
<h3><%= t('view.show') %></h3>

<p><%= notice %></p>

<p><span class="task_detail"><%= t('view.title') %>:</span> <span class="task_detail02"><%= @task.title %></span></p>
<p><span class="task_detail"><%= t('view.explanation') %>:</span> <span class="task_detail02"><%= @task.explanation %></span></p>
<p><span class="task_detail"><%= t('view.deadline') %>:</span> <span class="task_detail02"><%= @task.deadline %></span></p>
<p><span class="task_detail"><%= t('view.status') %>:</span> <span class="task_detail02"><%= t("enums.task.status.#{@task.status}") %></span></p>
<p><span class="task_detail"><%= t('view.priority') %>:</span> <span class="task_detail02"><%= t("enums.task.priority.#{@task.priority}") %></span></p>
<div>
  <span class="task_detail"><%= t('view.label') %>:</span>
  <% @task.labels.each do |label| %>
  <span><%= label.name %></span>
  <% end %>
</div>



<p class="to_other_page"><%= link_to t('view.edit'), edit_task_path(@task) %></p>
<p class="to_other_page"><%= link_to t('view.index'), tasks_path %></p>

app/views/users/new.html.erb
<h3><%= t('view.signup') %></h3>


<%= form_with(model: @user, local: true) do |f| %>

<% if @user.errors.any? %>
<div id="error_explanation">
  <h3><%= pluralize(@user.errors.count, "") %><%= t('view.cannot_save') %> </h3>
  <% @user.errors.full_messages.each do |message| %>
  <p><%= message %></p>
  <% end %>
</div>
<% end %>

  <div class="">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="">
  <%= f.label :email %>
  <%= f.text_field :email %>
  </div>

  <div class="">
  <%= f.label :password %>
  <%= f.text_field :password %>
  </div>

  <div class="">
  <%= f.label :password_confirmation %>
  <%= f.text_field :password_confirmation %>
  </div>

  <div class="">
  <%= f.submit t('view.create my account') %>
  </div>

<% end %>

app/views/users/show.html.erb
<h3><%= @user.name %><%= t('view.my_page') %></h3>

<div class="">
  <p class=""><%= t('view.registerd_task') %></p>
  <% @user.tasks.each do |task| %>
  <div class="user_registerd_tasks">
    <p><%= task.title %></p>
    <p><%= task.explanation %></p>
    <p><%= task.deadline %></p>
    <p><%= t("enums.task.status.#{task.status}") %></p>
    <p><%= t("enums.task.priority.#{task.priority}") %></p>
    <% task.labels.each do |label| %>
    <span><%= label.name %></span>
    <% end %>

    <p class="to_other_page">
      <%= link_to t('view.edit'), edit_task_path(task.id) %></p>
    <p class="to_other_page">
      <%= link_to t('view.destroy'), task_path(task.id), method: :delete, data: { confirm: t('view.destroy_confirm')} %></p>
  </div>
  <% end %>

  <p class="to_other_page">
    <%= link_to t('view.create'), new_task_path %></p>
  <p class="to_other_page">
    <%= link_to t('view.index'), tasks_path %></p>
  <p class="to_other_page">
      <%= link_to t('view.logout'), session_path(current_user.id), method: :delete %></p>

</div>